// TODO: DEV-13471
import * as WindowsKeyCode from 'keycode-js';
import UIEventsCode from '../UIEventsCode';

export const WindowsKeyCodeToKey = new Map([
    [WindowsKeyCode.KEY_BACK_QUOTE, UIEventsCode.Backquote],
    [WindowsKeyCode.KEY_BACK_SLASH, UIEventsCode.Backslash],
    [WindowsKeyCode.KEY_OPEN_BRACKET, UIEventsCode.BracketLeft],
    [WindowsKeyCode.KEY_CLOSE_BRACKET, UIEventsCode.BracketRight],
    [WindowsKeyCode.KEY_COMMA, UIEventsCode.Comma],
    [WindowsKeyCode.KEY_0, UIEventsCode.Digit0],
    [WindowsKeyCode.KEY_1, UIEventsCode.Digit1],
    [WindowsKeyCode.KEY_2, UIEventsCode.Digit2],
    [WindowsKeyCode.KEY_3, UIEventsCode.Digit3],
    [WindowsKeyCode.KEY_4, UIEventsCode.Digit4],
    [WindowsKeyCode.KEY_5, UIEventsCode.Digit5],
    [WindowsKeyCode.KEY_6, UIEventsCode.Digit6],
    [WindowsKeyCode.KEY_7, UIEventsCode.Digit7],
    [WindowsKeyCode.KEY_8, UIEventsCode.Digit8],
    [WindowsKeyCode.KEY_9, UIEventsCode.Digit9],
    [WindowsKeyCode.KEY_EQUALS, UIEventsCode.Equal],
    // [WindowsKeyCode.KEY_, UIEventsCode.IntlRo],
    // [WindowsKeyCode.KEY_, UIEventsCode.IntlYen],
    [WindowsKeyCode.KEY_A, UIEventsCode.KeyA],
    [WindowsKeyCode.KEY_B, UIEventsCode.KeyB],
    [WindowsKeyCode.KEY_C, UIEventsCode.KeyC],
    [WindowsKeyCode.KEY_D, UIEventsCode.KeyD],
    [WindowsKeyCode.KEY_E, UIEventsCode.KeyE],
    [WindowsKeyCode.KEY_F, UIEventsCode.KeyF],
    [WindowsKeyCode.KEY_G, UIEventsCode.KeyG],
    [WindowsKeyCode.KEY_H, UIEventsCode.KeyH],
    [WindowsKeyCode.KEY_I, UIEventsCode.KeyI],
    [WindowsKeyCode.KEY_J, UIEventsCode.KeyJ],
    [WindowsKeyCode.KEY_K, UIEventsCode.KeyK],
    [WindowsKeyCode.KEY_L, UIEventsCode.KeyL],
    [WindowsKeyCode.KEY_M, UIEventsCode.KeyM],
    [WindowsKeyCode.KEY_N, UIEventsCode.KeyN],
    [WindowsKeyCode.KEY_O, UIEventsCode.KeyO],
    [WindowsKeyCode.KEY_P, UIEventsCode.KeyP],
    [WindowsKeyCode.KEY_Q, UIEventsCode.KeyQ],
    [WindowsKeyCode.KEY_R, UIEventsCode.KeyR],
    [WindowsKeyCode.KEY_S, UIEventsCode.KeyS],
    [WindowsKeyCode.KEY_T, UIEventsCode.KeyT],
    [WindowsKeyCode.KEY_U, UIEventsCode.KeyU],
    [WindowsKeyCode.KEY_V, UIEventsCode.KeyV],
    [WindowsKeyCode.KEY_W, UIEventsCode.KeyW],
    [WindowsKeyCode.KEY_X, UIEventsCode.KeyX],
    [WindowsKeyCode.KEY_Y, UIEventsCode.KeyY],
    [WindowsKeyCode.KEY_Z, UIEventsCode.KeyZ],
    [WindowsKeyCode.KEY_SUBTRACT, UIEventsCode.Minus],
    [WindowsKeyCode.KEY_PERIOD, UIEventsCode.Period],
    [WindowsKeyCode.KEY_QUOTE, UIEventsCode.Quote],
    [WindowsKeyCode.KEY_SEMICOLON, UIEventsCode.Semicolon],
    [WindowsKeyCode.KEY_SLASH, UIEventsCode.Slash],
    // [WindowsKeyCode.KEY_, UIEventsCode.KanaMode],
    [WindowsKeyCode.KEY_DELETE, UIEventsCode.Delete],
    [WindowsKeyCode.KEY_END, UIEventsCode.End],
    [WindowsKeyCode.KEY_HELP, UIEventsCode.Help],
    [WindowsKeyCode.KEY_HOME, UIEventsCode.Home],
    [WindowsKeyCode.KEY_INSERT, UIEventsCode.Insert],
    [WindowsKeyCode.KEY_PAGE_DOWN, UIEventsCode.PageDown],
    [WindowsKeyCode.KEY_PAGE_UP, UIEventsCode.PageUp],
    // [WindowsKeyCode.KEY_, UIEventsCode.AltLeft],
    // [WindowsKeyCode.KEY_, UIEventsCode.AltRight],
    [WindowsKeyCode.KEY_BACK_SPACE, UIEventsCode.Backspace],
    [WindowsKeyCode.KEY_CAPS_LOCK, UIEventsCode.CapsLock],
    // [WindowsKeyCode.KEY_, UIEventsCode.ControlLeft],
    // [WindowsKeyCode.KEY_, UIEventsCode.ControlRight],
    [WindowsKeyCode.KEY_RETURN, UIEventsCode.Enter],
    // [WindowsKeyCode.KEY_, UIEventsCode.MetaLeft],
    // [WindowsKeyCode.KEY_, UIEventsCode.MetaRight],
    // [WindowsKeyCode.KEY_, UIEventsCode.ShiftLeft],
    // [WindowsKeyCode.KEY_, UIEventsCode.ShiftRight],
    [WindowsKeyCode.KEY_SPACE, UIEventsCode.Space],
    [WindowsKeyCode.KEY_TAB, UIEventsCode.Tab],
    [WindowsKeyCode.KEY_LEFT, UIEventsCode.ArrowLeft],
    [WindowsKeyCode.KEY_UP, UIEventsCode.ArrowUp],
    [WindowsKeyCode.KEY_RIGHT, UIEventsCode.ArrowRight],
    [WindowsKeyCode.KEY_DOWN, UIEventsCode.ArrowDown],

    [WindowsKeyCode.KEY_NUM_LOCK, UIEventsCode.NumLock],
    [WindowsKeyCode.KEY_NUMPAD0, UIEventsCode.Numpad0],
    [WindowsKeyCode.KEY_NUMPAD1, UIEventsCode.Numpad1],
    [WindowsKeyCode.KEY_NUMPAD2, UIEventsCode.Numpad2],
    [WindowsKeyCode.KEY_NUMPAD3, UIEventsCode.Numpad3],
    [WindowsKeyCode.KEY_NUMPAD4, UIEventsCode.Numpad4],
    [WindowsKeyCode.KEY_NUMPAD5, UIEventsCode.Numpad5],
    [WindowsKeyCode.KEY_NUMPAD6, UIEventsCode.Numpad6],
    [WindowsKeyCode.KEY_NUMPAD7, UIEventsCode.Numpad7],
    [WindowsKeyCode.KEY_NUMPAD8, UIEventsCode.Numpad8],
    [WindowsKeyCode.KEY_NUMPAD9, UIEventsCode.Numpad9],
    // [WindowsKeyCode.KEY_, UIEventsCode.NumpadAdd],
    // [WindowsKeyCode.KEY_, UIEventsCode.NumpadComma],
    // [WindowsKeyCode.KEY_, UIEventsCode.NumpadDecimal],
    // [WindowsKeyCode.KEY_, UIEventsCode.NumpadDivide],
    // [WindowsKeyCode.KEY_, UIEventsCode.NumpadEnter],
    // [WindowsKeyCode.KEY_, UIEventsCode.NumpadEqual],
    // [WindowsKeyCode.KEY_, UIEventsCode.NumpadMultiply],
    // [WindowsKeyCode.KEY_, UIEventsCode.NumpadParenLeft],
    // [WindowsKeyCode.KEY_, UIEventsCode.NumpadParenRight],
    // [WindowsKeyCode.KEY_, UIEventsCode.NumpadSubtract],

    [WindowsKeyCode.KEY_ESCAPE, UIEventsCode.Escape],
    [WindowsKeyCode.KEY_F1, UIEventsCode.F1],
    [WindowsKeyCode.KEY_F2, UIEventsCode.F2],
    [WindowsKeyCode.KEY_F3, UIEventsCode.F3],
    [WindowsKeyCode.KEY_F4, UIEventsCode.F4],
    [WindowsKeyCode.KEY_F5, UIEventsCode.F5],
    [WindowsKeyCode.KEY_F6, UIEventsCode.F6],
    [WindowsKeyCode.KEY_F7, UIEventsCode.F7],
    [WindowsKeyCode.KEY_F8, UIEventsCode.F8],
    [WindowsKeyCode.KEY_F9, UIEventsCode.F9],
    [WindowsKeyCode.KEY_F10, UIEventsCode.F10],
    [WindowsKeyCode.KEY_F11, UIEventsCode.F11],
    [WindowsKeyCode.KEY_F12, UIEventsCode.F12],
    // [WindowsKeyCode.KEY_, UIEventsCode.Fn],
    [WindowsKeyCode.KEY_PRINTSCREEN, UIEventsCode.PrintScreen],
    [WindowsKeyCode.KEY_PAUSE, UIEventsCode.Pause],
]);
//
