export enum WDAMethod {
    CLICK = 'CLICK',
    SCROLL = 'SCROLL',
    PRESS_BUTTON = 'PRESS_BUTTON',
    GET_SCREEN_WIDTH = 'GET_SCREEN_WIDTH',
    APPIUM_SETTINGS = 'APPIUM_SETTINGS',
    SEND_KEYS = 'SEND_KEYS',
    // TODO: HBsmith
    LOCK = 'LOCK',
    UNLOCK = 'UNLOCK',
    TERMINATE_APP = 'TERMINATE_APP',
    TAP_LONG = 'TAP_LONG',
    REBOOT = 'REBOOT',
    //
}
