export enum WDAMethod {
    CLICK = 'CLICK',
    SCROLL = 'SCROLL',
    PRESS_BUTTON = 'PRESS_BUTTON',
    GET_SCREEN_WIDTH = 'GET_SCREEN_WIDTH',
    // TODO: HBsmith DEV-14062, DEV-14620
    UNLOCK = 'UNLOCK',
    TERMINATE_APP = 'TERMINATE_APP',
    //
}
