export enum WdaStatus {
    STARTING = 'STARTING',
    STARTED = 'STARTED',
    STOPPED = 'STOPPED',
    // TODO: HBsmith
    ERROR = 'ERROR',
    IN_ACTION = 'IN_ACTION',
    END_ACTION = 'END_ACTION',
    SET_UP = 'SET_UP',
    SET_UP_DEVICE_INFO = 'SET_UP_DEVICE_INFO',
    SET_UP_GIT_INFO = 'SET_UP_GIT_INFO',
    SET_UP_SCREEN_ON = 'SET_UP_SCREEN_ON',
    END_SET_UP = 'END_SET_UP',
    //
}
